config/routes.rb
Rails.application.routes.draw do
  # Root path
  root to: 'home#index'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up', to: 'rails/health#show', as: :rails_health_check

  # Devise
  devise_for :users

  # Users
  get 'account/destroy', to: 'users#confirm_destroy', as: :confirm_destroy_user
  delete 'account/destroy', to: 'users#destroy', as: :destroy_user

  # Settings
  resources :settings, only: :index do
    collection do
      patch 'locale', to: 'settings#update_locale'
    end
  end

  # Home
  resources :home, only: %i[index]

  # Budget periods
  resources :budget_periods, path: :budgets, param: :uid, only: %i[index show]
  get 'budgets/:uid/details', to: 'budget_periods#details', as: :budget_period_details

  # Income transactions
  resources :budgets, only: [], param: :uid do
    resources :income_transactions, path: :income, except: %i[index show]
    resources :expense_transactions, path: :expense, except: %i[index show]
    get 'expenses/categories_chart', to: 'expense_transactions#categories_chart'
  end

  # Expense categories
  resources :expense_categories, except: :show

  # Todo Lists
  resources :todo_lists do
    resources :todo_tasks, only: %i[new create edit update destroy]
    resources :todo_categories, except: :show
  end
end

app/views/shared/_table_expense_row.html.erb
<tr>
  <td class="text-center">
    <%= link_to edit_budget_expense_transaction_path(data[:budget_period].uid, data[:expense]) do %>
      <%= image_tag "pencil.svg", alt: "more", class: "w-5" %>
    <% end %>
  </td>
  <td><%= data[:expense].description %></td>
  <td>
    <% if data[:expense].expense_category.default? %>
      <span class="text-slate-400">No category</span>
    <% else %>
      <span style="color: <%= data[:expense].expense_category.color %>;"><%= data[:expense].expense_category.name %></span>
    <% end %>
  </td>
  <td class="text-rose-600 number"><%= number_to_currency(data[:expense].amount) %></td>
  <td class="italic text-slate-500"><%= data[:expense].created_at.strftime('%A %d') %></td>
  <td class="text-center">
    <%= button_to budget_expense_transaction_path(data[:budget_period].uid, data[:expense]), method: :delete do %>
      <%= image_tag "bin.svg", alt: "more", class: "w-5" %>
    <% end %>
  </td>
</tr>